name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Remote Server
      env:
        DEPLOY_HOST: 13.212.154.92
        DEPLOY_USER: fangge
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key -r . $fangge@$13.212.154.92:/home/fangge/codes/langchain-demo
        rm -f deploy_key
